{"uuid": "8c0794c4-0ba0-4e69-ba9c-ae0d67a41530", "children": ["1491a474-4fbf-4399-903f-c68865c1f861"], "befores": [{"name": "browser_management", "status": "passed", "start": 1668590187267, "stop": 1668590198094}], "afters": [{"name": "browser_management::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=46999): Max retries exceeded with url: /session/889b86ab97c686d2c416f882902127ee/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ba93938e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/allure_commons/_allure.py\", line 209, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/_pytest/fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"/home/vlad/PycharmProjects/Codarium_course/todomvc_test/tests/conftest.py\", line 19, in browser_management\n    browser.clear_local_storage()\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/selene/core/entity.py\", line 1620, in clear_local_storage\n    self.driver.execute_script(\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 884, in execute_script\n    return self.execute(command, {\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 428, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 347, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 369, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/urllib3/request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/home/vlad/.cache/pypoetry/virtualenvs/codarium-course-J6QylXrB-py3.8/lib/python3.8/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1668590208480, "stop": 1668590208487}], "start": 1668590187267, "stop": 1668590208487}